# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 14

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels: []

# Label to use when marking as stale
staleLabel: 💤 Stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because there were no
  activity during last 14 days. It will be closed in 7 days if no further activity occurs.
  Thank you for your contributions.
  
  
  **А. Чому так?**
  
  Найбільш розповсюджена причина: Студент не реагує на коментарі змінами коду і не задає запитань
  через брак часу або зміну життєвих пріоритетів. Покинуті піари відволікають менторів.
  Коли у студента з'явиться час, він/вона зможе перевідкрити той самий піар і продовжити роботу.
  
  
  **Б. Що робити, якщо в піарі нема оновлень, оскільки не зрозуміло, що треба зробити?**
  
  Варіант 1. Задати питання в самому PR.
  
  Варіант 2. Задати питання в студентському чаті.
  
  
  **В. А якщо я все зробив(ла) і це ментор не рев'юває мої зміни?**
  
  1. Переконайся, що ти відреагував(ла) на всі коментарі або кодом, або запитаннями, або відповідями.
  Напиши в PR і в чаті, що чесно вважаєш, що все зроблено і попроси повторне рев'ю. Якщо щось не зрозуміло, задай запитання.
  
  2. Реагуй на коментарі як менторів, так і інших учасників, включаючи ботів.
  
  3. Не ігноруй прохання типу
  * "Let's do some self-checks ..."
  * "Go through the checklist below..."
  * "mark fulfilled requirements..."
  * "if you would silently ignore this recommendation, a mentor may think that you are still working on fixes"
  
  навіть якщо вони написані ботом. Боти помічники і ментори покладаються на те, що прохання і пропозиції бота дотримуються.
  
  Не лінись піти по лінках в коментарях, погуглити термінологію та скористатись Google Translate.
  
  4. Можливо, у менторів склалися інші пріоритети через роботу, сімейні обставини і т.п.
  В такому разі, якщо ти зробив(ла) рекомендоване вище, то волай в чаті, що PR позначений stale,
  наче, все зроблено, а ментори чомусь не реагують - рятуйте!
  
  
  **Г. Хіба недостатньо того, що я додав(ла) коміт із змінами?**
  
  Часто буває так, що бачиш новий коміт, ідеш перевіряти, змін багато, доводиться перечитувати весь код.
  А потім з'ясовується, що одна невеличка зміна "відкладена на потім" чи з'являється ще один коміт
  і знов треба перечитувати все. Любіть нас, спілкуйтеся з нами - і ми відповімо повною взаємністю.
  
  
  Традиційна пропозиція: задай питання по вищенаписаному в студентському чаті.
