const cities = [
  {
    id: 'kyiv',
    name: 'Київ',
    state: 'Київська область',
    img: 'images/Kyiv.jpg',
    emblem: 'images/emblem/emblemKyiv.png',
    source: 'Фото: взято з Wikipedia',
    population: '2 962 180',
    area: '839 км2',
    founded: '482 г.',
    code: '+380 44',
    registration: 'AA, KA',
    cityday: 'остання неділя травня',
  },
  {
    id: 'lviv',
    name: 'Львів',
    state: 'Львівська область',
    img: 'images/Lviv.jpg',
    emblem: 'images/emblem/emblemLviv.png',
    source: 'Фото: взято з Wikipedia',
    population: '717 273',
    area: '148.95 км2',
    founded: '1256 г.',
    code: '+380 32',
    registration: 'BC, HC',
    cityday: 'перша неділя травня',
  },
  {
    id: 'mykolaiv',
    name: 'Миколаїв',
    state: 'Миколаївська область',
    img: 'images/Mykolaiv.jpg',
    emblem: 'images/emblem/emblemMykolaiv.png',
    source: 'Фото: взято з Wikipedia',
    population: '470 011',
    area: '252,8261 км2',
    founded: '1789 г.',
    code: '+380 512',
    registration: 'ВЕ',
    cityday: 'Друга субота після першого вересня',
  },
  {
    id: 'odesa',
    name: 'Одеса',
    state: 'Одеська область',
    img: 'images/Odesa.jpg',
    emblem: 'images/emblem/emblemOdesa.png',
    source: 'Фото: взято з Wikipedia',
    population: '1 010 537',
    area: '162,42 км2',
    founded: '1415 г.',
    code: '+380 48',
    registration: 'ВН, НН',
    cityday: '2 вересня',
  },
  {
    id: 'ternopil',
    name: 'Тернопіль',
    state: 'Тернопільська область',
    img: 'images/Ternopil.jpg',
    emblem: 'images/emblem/emblemTernopil.png',
    source: 'Фото: взято з Wikipedia',
    population: '225 004',
    area: '72 км2',
    founded: '1540 г.',
    code: '+380 352',
    registration: 'ВО, НО',
    cityday: '28 серпня',
  },
  {
    id: 'kharkiv',
    name: 'Харків',
    state: 'Харківська область',
    img: 'images/Kharkiv.jpg',
    emblem: 'images/emblem/emblemKharkiv.png',
    source: 'Фото: взято з Wikipedia',
    population: '1 421 125',
    area: '350 км2',
    founded: '1654 г.',
    code: '+380 57',
    registration: 'АХ, КХ',
    cityday: '23 серпня',
  },
  {
    id: 'kherson',
    name: 'Херсон',
    state: 'Херсонська область',
    img: 'images/Kherson.jpg',
    emblem: 'images/emblem/emblemKherson.png',
    source: 'Фото: взято з Wikipedia',
    population: '279 131',
    area: '145 км2',
    founded: '1778 г.',
    code: '+380 552',
    registration: 'ВТ, НТ',
    cityday: '3-я неділя вересня',
  },
  {
    id: 'chernivtsi',
    name: 'Чернівці',
    state: 'Чернівецька область',
    img: 'images/Chernivtsi.jpg',
    emblem: 'images/emblem/emblemChernivtsi.png',
    source: 'Фото: взято з Wikipedia',
    population: '264 298',
    area: '153 км2',
    founded: '1408 г.',
    code: '+380 372',
    registration: 'СЕ, IЕ',
    cityday: 'перші субота — неділя жовтня',
  },
];

export default cities;
